{% set name = "neptune-lightgbm" %}
{% set version = "0.9.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neptune-ai/{{ name }}/archive/{{ version }}.tar.gz
  sha256: be65cbab3172ae4b8d1c9af13679318cfb46ee15014b9f3d92dc1a37b24ea5b6

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - neptune-client >=0.9
    - python >=3.6
    - lightgbm
    - matplotlib-base
    - scikit-plot
    - graphviz

test:
  imports:
    - neptune_lightgbm
    - neptune_lightgbm.impl

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune Client integration with LightGBM
  doc_url: https://github.com/neptune-ai/neptune-lightgbm/blob/master/README.md
  dev_url: https://github.com/neptune-ai/neptune-lightgbm

extra:
  recipe-maintainers:
    - aniezurawski
    - HubertJaworski
    - pitercl
    - PiotrJander
    - shnela
    - pkasprzyk
