{% set name = "neptune-lightgbm" %}
{% set version = "0.9.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neptune-ai/{{ name }}/archive/{{ version }}.tar.gz
  sha256: d6c1c8aff1fcc6c798e3d686c643d0259780306a1a69eb84acd6e97ce7552542

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - neptune-client >=0.9
    - python >=3.6
    - lightgbm
    - matplotlib-base

test:
  imports:
    - neptune_lightgbm
    - neptune_lightgbm.impl

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune Client integration with LightGBM
  doc_url: https://github.com/neptune-ai/neptune-lightgbm/blob/master/README.md
  dev_url: https://github.com/neptune-ai/neptune-lightgbm

extra:
  recipe-maintainers:
    - aniezurawski
    - HubertJaworski
    - pitercl
    - PiotrJander
    - shnela
    - pkasprzyk
