{% set name = "neptune-lightgbm" %}
{% set package_name = "neptune_lightgbm" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ package_name }}-{{ version }}.tar.gz
  sha256: c748ad2f3a36e07e09a57aa4782b01a0dbcda8f2930cb94e48037a10bea5aa68

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3.6
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
  run:
    - neptune-client >=0.9
    - python >=3.6
    - lightgbm
    - matplotlib-base
    - scikit-plot
    - graphviz

test:
  imports:
    - neptune_lightgbm
    - neptune_lightgbm.impl

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune Client integration with LightGBM
  doc_url: https://github.com/neptune-ai/neptune-lightgbm/blob/master/README.md
  dev_url: https://github.com/neptune-ai/neptune-lightgbm

extra:
  recipe-maintainers:
    - aniezurawski
    - HubertJaworski
    - pitercl
    - Raalsky
    - shnela
    - twolodzko
    - AleksanderWWW
    - PatrykGala
